"use client";
import { useCallback,useEffect,useState } from 'react';
import { Badge,Field,Table,api,date,styles } from './shared';
import RuleEditor, { type RuleRow, type VersionRow } from './RuleEditor';
import TemplateEditor from './TemplateEditor';
import CustomerJourney from './CustomerJourney';
type Row=Record<string,unknown>&{id:string};
type Overview={processing:number;retrying:number;dlq:number;outbox_backlog:number;outbox_oldest_at:string|null;sample_limit:number;dry_run:boolean;providers:{name:string;status:string;last_success:string|null;last_failure:string|null;success_rate:number|null;latency_ms:number|null;pending:number;retrying:number}[];daily:{date:string;queued:number;accepted:number;delivered:number;engaged:number;failed:number}[];};
const tabs=['Overview','Rules','Runs','Templates','Deliveries','Providers','DLQ'] as const;
export default function Communications(){
 const [tab,select]=useState<typeof tabs[number]>('Overview');const [rows,setRows]=useState<Row[]>([]);const [versions,setVersions]=useState<VersionRow[]>([]);const [templates,setTemplates]=useState<Row[]>([]);const [artifacts,setArtifacts]=useState<Row[]>([]);const [overview,setOverview]=useState<Overview|null>(null);
 const [role,setRole]=useState('VIEWER');const [notice,message]=useState('');const [loading,setLoading]=useState(false);const [cursor,setCursor]=useState<string|null>(null);
 const [failedOutbox,setFailedOutbox]=useState<Row[]>([]);const [outboxCursor,setOutboxCursor]=useState<string|null>(null);
 const [ruleEditor,editRule]=useState<RuleRow|null|undefined>();const [templateEditor,editTemplate]=useState<(VersionRow&{logical_key?:string;name?:string})|null|undefined>();const [mapping,editMapping]=useState<Row|null>(null);const [testVersion,setTestVersion]=useState<string|null>(null);const [testDestination,setTestDestination]=useState('');
 const load=useCallback(async(after?:string)=>{setLoading(true);try{
  const resource=tab.toLowerCase();const result=await api(`/api/admin/communications?resource=${resource}${after?`&cursor=${after}`:''}`);setRole(result.role);
  if(tab==='Overview'||tab==='Providers')setOverview(result.data);else{setRows(result.data);setCursor(result.next_cursor);}
  if(tab==='DLQ'){const failed=await api('/api/admin/communications?resource=outbox_dlq');setFailedOutbox(failed.data);setOutboxCursor(failed.next_cursor);}
  if(tab==='Rules'||tab==='Templates'){
   const [v,t,a]=await Promise.all(['versions','templates','artifacts'].map(r=>api(`/api/admin/communications?resource=${r}`)));setVersions(v.data);setTemplates(t.data);setArtifacts(a.data);
  }
 }catch(e){message((e as Error).message);}finally{setLoading(false);}},[tab]);
 useEffect(()=>{load();editRule(undefined);editTemplate(undefined);},[load]);
 async function mutate(operation:string,input:unknown){try{await api('/api/admin/communications',{operation,input});message('Saved.');await load();}catch(e){message((e as Error).message);}}
 const admin=role==='ADMIN';const templateName=(id:string)=>String(templates.find(t=>t.id===id)?.name||id.slice(0,8));
 const saveRuleStatus=(r:RuleRow,status:string)=>{const {id,version,next_run_at,last_status,last_completed_at,...draft}=r;const allowed={name:draft.name,description:draft.description||'',status,trigger_type:draft.trigger_type,trigger_event_type:draft.trigger_event_type,cron_expression:draft.cron_expression,timezone:draft.timezone,condition_config:draft.condition_config,action_config:draft.action_config,frequency_cap:draft.frequency_cap,quiet_hours:draft.quiet_hours,priority:draft.priority,valid_from:draft.valid_from,valid_until:draft.valid_until};return mutate('SAVE_RULE',{id,expected_version:version,rule:allowed});};
 return <section className={styles.shell}><h1>Communications</h1><p>Rules, canonical content and delivery operations.</p><div className={styles.tabs} role="tablist" aria-label="Communications sections">{tabs.map(t=><button key={t} role="tab" aria-selected={tab===t} onClick={()=>select(t)}>{t}</button>)}<button onClick={()=>load()} disabled={loading}>Refresh</button></div>
  {notice&&<p role="status" className={styles.notice}>{notice}</p>}{loading&&<p role="status">Loading…</p>}
  {(tab==='Overview'||tab==='Providers')&&overview&&<>
   {overview.dry_run&&<div className={styles.notice}>Dry run enabled. External sends require an allowlisted destination.</div>}
   {tab==='Overview'&&<><div className={styles.grid}>{[['Processing',overview.processing],['Retrying',overview.retrying],['Needs attention',overview.dlq],['Outbox backlog',overview.outbox_backlog]].map(([label,n])=><div className={styles.panel} key={label}><span>{label}</span><div className={styles.metric}>{n}</div></div>)}</div><p className={styles.small}>Operational sample capped at {overview.sample_limit} recent records. Oldest pending event: {date(overview.outbox_oldest_at)}.</p><Table columns={['Day','Queued','Accepted / sent','Delivered','Read / opened / clicked','Failed']} rows={overview.daily.map(d=>[d.date,d.queued,d.accepted,d.delivered,d.engaged,d.failed])}/></>}
   <h2>Provider observations</h2><Table columns={['Provider','Status','Last success','Last failure','Success rate','Latency','Pending','Retrying']} rows={overview.providers.map(p=>[p.name,<Badge key={p.name} value={p.status}/>,date(p.last_success),date(p.last_failure),p.success_rate===null?'—':`${p.success_rate}%`,p.latency_ms===null?'—':`${p.latency_ms} ms`,p.pending,p.retrying])}/>
  </>}
  {tab==='Rules'&&<><div className={styles.toolbar}><button disabled={!admin} onClick={()=>editRule(null)}>Create rule</button></div>{ruleEditor!==undefined&&<RuleEditor key={ruleEditor?.id||'new'} initial={ruleEditor} versions={versions} onCancel={()=>editRule(undefined)} onSave={()=>{editRule(undefined);load();}}/>}<Table columns={['Rule','Status','Trigger','Schedule / timezone','Audience','Channels / templates','Last run','Next run','Actions']} rows={(rows as unknown as RuleRow[]).map(r=>[r.name,<Badge key={r.id} value={r.status}/>,r.trigger_type==='EVENT'?r.trigger_event_type:r.trigger_type,`${r.cron_expression||'—'} · ${r.timezone}`,'Feature conditions',Object.entries(r.action_config.templates).map(([c,id])=>`${c}: ${versions.find(v=>v.id===id)?.subject||id.slice(0,8)}`).join(', '),`${date(r.last_completed_at)} · ${r.last_status||'—'}`,date(r.next_run_at),<div className={styles.toolbar} key={r.id}><button disabled={!admin} onClick={()=>editRule(r)}>Edit</button><button disabled={!admin} onClick={()=>editRule({...r,id:'',name:r.name+' copy',status:'DRAFT'} as RuleRow)}>Clone</button><button disabled={!admin} onClick={()=>saveRuleStatus(r,r.status==='ACTIVE'?'PAUSED':'ACTIVE')}>{r.status==='ACTIVE'?'Pause':'Resume'}</button><button disabled={!admin} onClick={()=>saveRuleStatus(r,'ARCHIVED')}>Archive</button><button disabled={!admin||r.status!=='ACTIVE'} onClick={()=>mutate('RUN_RULE',{id:r.id,request_key:crypto.randomUUID(),dry_run:true})}>Dry run</button><button disabled={!admin||r.status!=='ACTIVE'} onClick={()=>mutate('RUN_RULE',{id:r.id,request_key:crypto.randomUUID(),dry_run:false})}>Run now</button></div>])}/></>}
  {tab==='Templates'&&<><button disabled={!admin} onClick={()=>editTemplate(null)}>New template</button>{templateEditor!==undefined&&<TemplateEditor key={templateEditor?.id||'new'} initial={templateEditor} onSaved={()=>{editTemplate(undefined);load();}} onCancel={()=>editTemplate(undefined)}/>}{mapping&&<form className={styles.panel} onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);const input=Object.fromEntries([...form].filter(([,v])=>v!==''));mutate('MAP_PROVIDER',{version_id:mapping.template_version_id,...input});editMapping(null);}}><h2>Provider mapping · {String(mapping.provider)}</h2><div className={styles.grid}>{(mapping.provider==='META_WHATSAPP'?['provider_template_name','provider_language']:mapping.provider==='MSG91'?['dlt_entity_id','dlt_header_id','dlt_template_id','dlt_status','msg91_template_id','msg91_status']:mapping.provider==='LEMLIST'?['lemlist_campaign_id','lemlist_sequence_id','lemlist_step_id']:['provider_template_id','sync_mode']).map(field=><Field key={field} label={field.replace(/_/g,' ')}><input name={field} defaultValue={String(mapping[field]||'')}/></Field>)}</div><p>Meta approval is supplied by its API or signed webhook. DLT approval must come from the telecom authority.</p><button>Save mapping</button><button type="button" onClick={()=>editMapping(null)}>Cancel</button></form>}
   <Table columns={['Template','Version','Channel','Category','Canonical status','Provider status','Actions']} rows={versions.map(v=>{const a=artifacts.find(a=>a.template_version_id===v.id);return [templateName(v.template_id),v.version,v.channel,v.category,<Badge key="canonical" value={v.status}/>,<Badge key="provider" value={String(a?.provider_status||'UNKNOWN')}/>,<div className={styles.toolbar} key={v.id}><button disabled={!admin} onClick={()=>editTemplate({...v,logical_key:String(templates.find(t=>t.id===v.template_id)?.logical_key||''),name:templateName(v.template_id)})}>New version</button><button disabled={!admin||v.status!=='DRAFT'} onClick={()=>editMapping(a||null)}>Map provider</button><button disabled={!admin||v.status!=='DRAFT'} onClick={()=>mutate('SUBMIT_PROVIDER',{id:v.id})}>Submit / sync</button><button disabled={!admin||a?.provider!=='META_WHATSAPP'} onClick={()=>mutate('REFRESH_PROVIDER',{id:v.id})}>Refresh approval</button><button disabled={!admin||v.status!=='DRAFT'} onClick={()=>mutate('ACTIVATE_TEMPLATE',{id:v.id})}>Activate</button></div>];})}/></>}
  {tab==='Runs'&&<Table columns={['Run','Status','Contacts processed','Batches','Last query','Started','Completed','Result']} rows={rows.map(r=>[r.id.slice(0,8),<Badge key={r.id} value={String(r.status)}/>,String(r.contacts_processed),String(r.batch_count),`${r.query_duration_ms} ms`,date(r.started_at),date(r.completed_at),String(r.last_error||'—')])}/>}
  {(tab==='Deliveries'||tab==='DLQ')&&<Table columns={['Delivery','Channel','Provider','Status','Attempts','Next attempt','Latency','Reason','Actions']} rows={rows.map(r=>[r.id.slice(0,8),String(r.channel),String(r.provider),<Badge key={r.id} value={String(r.status)}/>,String(Number(r.retry_count)+1),date(r.next_attempt_at),r.latency_ms===null?'—':`${r.latency_ms} ms`,String(r.suppression_reason||'—'),r.status==='FAILED_PERMANENT'?<button disabled={!admin} onClick={()=>mutate('RETRY_DELIVERY',{id:r.id})}>Retry after fixing cause</button>:r.status==='RECONCILIATION_PENDING'?'Verify provider outcome before retry':'—'])}/>}
  {tab==='DLQ'&&<><h2>Failed durable work</h2><Table columns={['Event','Operation','Lane','Attempts','Reason','Actions']} rows={failedOutbox.map(r=>[String(r.event_type),String(r.operation),String(r.lane),String(r.attempt_count),String(r.last_error_code),r.last_error_code==='TRANSPORT_ATTEMPTS_EXHAUSTED'?<button key={r.id} disabled={!admin} onClick={()=>mutate('RETRY_OUTBOX',{id:r.id})}>Replay after fixing transport</button>:'Repair the rule and start a new run'])}/>{outboxCursor&&<button onClick={async()=>{try{const next=await api(`/api/admin/communications?resource=outbox_dlq&cursor=${outboxCursor}`);setFailedOutbox(next.data);setOutboxCursor(next.next_cursor);}catch(e){message((e as Error).message);}}}>Next 100 failed events</button>}</>}
  {tab==='Providers'&&<>
   <CustomerJourney/>
   <form className={styles.panel} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);mutate('SAVE_PREFERENCE',{customer_id:f.get('customer_id'),channel:f.get('channel'),purpose:f.get('purpose'),allowed:f.get('allowed')==='true',evidence_reference:f.get('evidence_reference')});}}><h2>Record a communication preference</h2><p>Record existing consent or an opt-out with its evidence reference. This action does not collect consent from the customer.</p><div className={styles.grid}><Field label="Customer ID"><input name="customer_id" required placeholder="Customer UUID"/></Field><Field label="Channel"><select name="channel">{['EMAIL','WHATSAPP','SMS'].map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Purpose"><select name="purpose"><option>MARKETING</option><option>TRANSACTIONAL</option></select></Field><Field label="Permission"><select name="allowed"><option value="false">Denied / opted out</option><option value="true">Allowed with recorded evidence</option></select></Field><Field label="Evidence reference"><input name="evidence_reference" required maxLength={500} placeholder="Consent receipt or support record"/></Field></div><button disabled={!admin}>Record preference</button></form>
   <form className={styles.panel} onSubmit={e=>{e.preventDefault();mutate('RECOVER_STATE',{source:new FormData(e.currentTarget).get('source')});}}><h2>Backfill feature state</h2><p>Processes the next 100 records using a durable cursor. Historical backfill updates projections without launching campaigns. Repeat until the source is complete.</p><Field label="Source"><select name="source">{['orders','subscriptions','payments','shipments'].map(s=><option key={s}>{s}</option>)}</select></Field><button disabled={!admin}>Queue next recovery batch</button></form>
  </>}
  {tab==='Templates'&&<form className={styles.panel} onSubmit={e=>{e.preventDefault();mutate('TEST_TEMPLATE',{id:testVersion,destination:testDestination});}}><h2>Queue a template test</h2><div className={styles.grid}><Field label="Version"><select required value={testVersion||''} onChange={e=>setTestVersion(e.target.value)}><option value="">Choose a version</option>{versions.map(v=><option key={v.id} value={v.id}>{templateName(v.template_id)} · {v.channel} · v{v.version}</option>)}</select></Field><Field label="Test email or phone"><input required value={testDestination} onChange={e=>setTestDestination(e.target.value)}/></Field></div><p>Only configured test allowlists may receive this send. Other destinations are recorded as DRY RUN.</p><button disabled={!admin}>Queue test</button></form>}
  {cursor&&!['Overview','Providers','Templates'].includes(tab)&&<button onClick={()=>load(cursor)}>Next 100 records</button>}
 </section>;
}
