"use client";
import { useCallback,useEffect,useState } from 'react';
import { z } from 'zod';
import { offerSchema,offerEditableFields } from '../../lib/admin/offersSchema';
import type { CartQuote } from '../../lib/commerce/types';
import { Badge,Field,Table,api,date,styles } from './shared';
type Draft=z.infer<typeof offerSchema>;type Offer=Draft&{id:string;version:number;usage_count:number};
const empty:Draft={code:'',label:'',status:'DRAFT',conditions:{},actions:[{type:'PERCENT_OFF',percent:10,scope:'CART'}],priority:0,stackable:false};
const arrays=['skus','product_codes','required_product_codes','customer_cohorts','countries'];
const numbers=['minimum_cart_value_paise','minimum_quantity','minimum_subscription_cycle','maximum_subscription_cycle'];
const booleans=['requires_entitlement','first_order_only','returning_customer_only'];
export default function Offers(){
 const [rows,setRows]=useState<Offer[]>([]);const [role,setRole]=useState('VIEWER');const [view,setView]=useState('All');const [selected,select]=useState<Offer|null>(null);const [draft,setDraft]=useState<Draft|null>(null);const [reason,setReason]=useState('');const [notice,message]=useState('');const [history,setHistory]=useState<{version:number;change_reason:string;created_at:string}[]>([]);
 const [sim,setSim]=useState({sku:'',qty:1,purchase_mode:'BUY_ONCE',interval_days:30,stage:'INITIAL',cycle_number:1,customer_type:'NEW',country:'IN'});const [quote,setQuote]=useState<CartQuote|null>(null);
 const load=useCallback(async()=>{try{const r=await api('/api/admin/offers');setRows(r.data);setRole(r.role);}catch(e){message((e as Error).message);}},[]);useEffect(()=>{load();},[load]);
 const admin=role==='ADMIN';const update=(key:keyof Draft,value:unknown)=>setDraft(draft?{...draft,[key]:value}:null);
 function edit(offer:Offer,clone=false){const content=offerEditableFields(offer);select(clone?null:offer);setDraft(clone?{...content,code:content.code+'_COPY',status:'DRAFT'}:content);setReason('');setHistory([]);}
 async function save(content:Draft,id?:string,version?:number,changeReason=reason){try{await api('/api/admin/offers',{operation:'SAVE',input:{id:id||null,expected_version:version,offer:offerEditableFields(content),change_reason:changeReason}});message('Offer saved. Historical order snapshots remain unchanged.');setDraft(null);await load();}catch(e){message((e as Error).message);}}
 const filtered=rows.filter(o=>view==='All'||view==='Scheduled'&&o.status==='ACTIVE'&&Date.parse(o.valid_from||'')>Date.now()||view!=='Scheduled'&&o.status===view.toUpperCase()&&(view!=='Active'||!o.valid_from||Date.parse(o.valid_from)<=Date.now()));
 function condition(key:string,value:unknown){const current={...draft!.conditions} as Record<string,unknown>;if(value===undefined||value===''||Array.isArray(value)&&!value.length)delete current[key];else current[key]=value;update('conditions',current);}
 return <section className={styles.shell}><h1>Offers</h1><p>Manage the promotions used by authoritative initial and renewal pricing. Amounts are integer paise.</p><div className={styles.tabs}>{['All','Active','Scheduled','Draft','Paused','Archived'].map(v=><button aria-pressed={view===v} key={v} onClick={()=>setView(v)}>{v}</button>)}<button disabled={!admin} onClick={()=>{select(null);setDraft({...empty,conditions:{},actions:[...empty.actions]});setReason('');}}>Create offer</button><button onClick={load}>Refresh</button></div>{notice&&<p className={styles.notice} role="status">{notice}</p>}
  {draft&&<form className={styles.panel} onSubmit={e=>{e.preventDefault();save(draft,selected?.id,selected?.version);}}><h2>{selected?'Edit offer':'Create offer'}</h2><div className={styles.grid}>
   <Field label="Code"><input required value={draft.code} onChange={e=>update('code',e.target.value.toUpperCase())}/></Field><Field label="Label"><input required value={draft.label} onChange={e=>update('label',e.target.value)}/></Field><Field label="Status"><select value={draft.status} onChange={e=>update('status',e.target.value)}>{['DRAFT','ACTIVE','PAUSED','ARCHIVED'].map(v=><option key={v}>{v}</option>)}</select></Field>
   <Field label="Valid from (ISO / UTC)"><input value={draft.valid_from||''} onChange={e=>update('valid_from',e.target.value||null)} placeholder="2026-10-10T04:30:00Z"/></Field><Field label="Valid until (ISO / UTC)"><input value={draft.valid_until||''} onChange={e=>update('valid_until',e.target.value||null)}/></Field><Field label="Priority"><input type="number" value={draft.priority} onChange={e=>update('priority',Number(e.target.value))}/></Field><Field label="Stacking group"><input value={draft.stacking_group||''} onChange={e=>update('stacking_group',e.target.value||null)}/></Field><Field label="Usage limit"><input type="number" min={1} value={draft.usage_limit||''} onChange={e=>update('usage_limit',e.target.value?Number(e.target.value):null)}/></Field>
  </div><label><input type="checkbox" checked={draft.stackable} onChange={e=>update('stackable',e.target.checked)}/>Stackable</label><h2>Eligibility conditions</h2><div className={styles.grid}>
   {arrays.map(key=><Field label={key.replace(/_/g,' ')+' (comma separated)'} key={key}><input value={((draft.conditions as Record<string,unknown>)[key] as string[]|undefined)?.join(', ')||''} onChange={e=>condition(key,e.target.value.split(',').map(v=>v.trim()).filter(Boolean))}/></Field>)}
   {numbers.map(key=><Field label={key.replace(/_/g,' ')} key={key}><input type="number" min={0} value={String((draft.conditions as Record<string,unknown>)[key]??'')} onChange={e=>condition(key,e.target.value?Number(e.target.value):undefined)}/></Field>)}
   <Field label="Audience"><select value={draft.conditions.audience||'ALL'} onChange={e=>condition('audience',e.target.value)}>{['ALL','NEW_SUBSCRIBERS','EXISTING_SUBSCRIBERS','NEW_SUBSCRIBERS_AND_BUYERS'].map(v=><option key={v}>{v}</option>)}</select></Field>
   <Field label="Purchase modes"><select value={draft.conditions.purchase_modes?.join(',')||''} onChange={e=>condition('purchase_modes',e.target.value?e.target.value.split(','):undefined)}>{[['','Any'],['BUY_ONCE','Buy once'],['SUBSCRIPTION','Subscription'],['BUY_ONCE,SUBSCRIPTION','Either'],['MIXED','Mixed checkout']].map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></Field>
   <Field label="Lifecycle"><select value={draft.conditions.lifecycle?.join(',')||''} onChange={e=>condition('lifecycle',e.target.value?e.target.value.split(','):undefined)}><option value="">Any</option><option>INITIAL</option><option>RENEWAL</option><option value="INITIAL,RENEWAL">Both</option></select></Field>
  </div><div className={styles.toolbar}>{booleans.map(key=><label key={key}><input type="checkbox" checked={Boolean((draft.conditions as Record<string,unknown>)[key])} onChange={e=>condition(key,e.target.checked||undefined)}/>{key.replace(/_/g,' ')}</label>)}</div>
  <h2>Actions</h2>{draft.actions.map((action,index)=><div className={styles.panel} key={index}><div className={styles.grid}><Field label="Action"><select value={action.type} onChange={e=>update('actions',draft.actions.map((a,i)=>i===index?{type:e.target.value,scope:'CART'}:a))}>{['AMOUNT_OFF','PERCENT_OFF','FIXED_BUNDLE_PRICE','FREE_SHIPPING','SHIPPING_DISCOUNT','FREE_GIFT','FREE_GIFT_WRAP','BUY_X_GET_Y','INFORMATIONAL'].map(t=><option key={t}>{t}</option>)}</select></Field><Field label="Scope"><select value={action.scope||'CART'} onChange={e=>update('actions',draft.actions.map((a,i)=>i===index?{...a,scope:e.target.value}:a))}>{['CART','MATCHING_LINES','SHIPPING'].map(v=><option key={v}>{v}</option>)}</select></Field>{(['amount_paise','percent','fixed_price_paise'] as const).filter(k=>k==='percent'?action.type==='PERCENT_OFF':k==='fixed_price_paise'?action.type==='FIXED_BUNDLE_PRICE':['AMOUNT_OFF','SHIPPING_DISCOUNT'].includes(action.type)).map(key=><Field label={key.replace(/_/g,' ')} key={key}><input type="number" min={0} max={key==='percent'?100:undefined} required value={action[key]??''} onChange={e=>update('actions',draft.actions.map((a,i)=>i===index?{...a,[key]:Number(e.target.value)}:a))}/></Field>)}<Field label="Action label"><input value={action.label||''} onChange={e=>update('actions',draft.actions.map((a,i)=>i===index?{...a,label:e.target.value}:a))}/></Field></div><button type="button" onClick={()=>update('actions',draft.actions.filter((_,i)=>i!==index))}>Remove action</button></div>)}<button type="button" onClick={()=>update('actions',[...draft.actions,{type:'INFORMATIONAL',label:''}])}>Add action</button>
  <Field label="Change reason"><input required value={reason} onChange={e=>setReason(e.target.value)}/></Field><div className={styles.toolbar}><button className={styles.primary}>Save version</button><button type="button" onClick={()=>setDraft(null)}>Cancel</button></div>
  </form>}
  <Table columns={['Code / label','Status','Validity','Priority / stacking','Usage','Version','Actions']} rows={filtered.map(o=>[`${o.code} · ${o.label}`,<Badge key={o.id} value={o.status}/>,`${date(o.valid_from)} → ${date(o.valid_until)}`,`${o.priority} · ${o.stacking_group||'No group'} · ${o.stackable?'Stackable':'Exclusive'}`,`${o.usage_count} / ${o.usage_limit||'Unlimited'}`,o.version,<div key={o.id} className={styles.toolbar}><button disabled={!admin} onClick={()=>edit(o)}>Edit</button><button disabled={!admin} onClick={()=>edit(o,true)}>Clone</button><button disabled={!admin} onClick={()=>{const{id,version,usage_count,...content}=o;save({...content,status:o.status==='ACTIVE'?'PAUSED':'ACTIVE'},id,version,'Operator status change');}}>{o.status==='ACTIVE'?'Pause':'Resume'}</button><button disabled={!admin} onClick={()=>{const{id,version,usage_count,...content}=o;save({...content,status:'ARCHIVED'},id,version,'Archived by operator');}}>Archive</button><button onClick={async()=>{try{const r=await api(`/api/admin/offers?history=${o.id}`);setHistory(r.data);}catch(e){message((e as Error).message);}}}>History</button></div>])}/>
  {history.length>0&&<div className={styles.panel}><h2>Version history</h2><Table columns={['Version','Reason','Changed at']} rows={history.map(h=>[h.version,h.change_reason,date(h.created_at)])}/></div>}
  <form className={styles.panel} onSubmit={async e=>{e.preventDefault();try{const r=await api('/api/admin/offers',{operation:'SIMULATE',input:{items:[{line_id:'simulation',sku:sim.sku,qty:sim.qty,purchase_mode:sim.purchase_mode,...(sim.purchase_mode==='SUBSCRIPTION'?{interval_days:sim.interval_days}:{})}],stage:sim.stage,cycle_number:sim.cycle_number,customer_type:sim.customer_type,country:sim.country,...(draft?{offer:draft}:{})}});setQuote(r.data);}catch(e){message((e as Error).message);}}}><h2>Test with server pricing</h2><div className={styles.grid}>
  <Field label="SKU"><input required value={sim.sku} onChange={e=>setSim({...sim,sku:e.target.value})}/></Field><Field label="Quantity"><input type="number" min={1} max={100} value={sim.qty} onChange={e=>setSim({...sim,qty:Number(e.target.value)})}/></Field>{(['purchase_mode','interval_days','stage','customer_type','country'] as const).map(key=><Field key={key} label={key.replace(/_/g,' ')}><select value={sim[key]} onChange={e=>setSim({...sim,[key]:key==='interval_days'?Number(e.target.value):e.target.value})}>{(key==='purchase_mode'?['BUY_ONCE','SUBSCRIPTION']:key==='interval_days'?[15,30,60]:key==='stage'?['INITIAL','RENEWAL']:key==='country'?['IN']:['NEW','RETURNING','SUBSCRIBER']).map(v=><option key={v}>{v}</option>)}</select></Field>)}<Field label="Cycle number"><input type="number" min={1} value={sim.cycle_number} onChange={e=>setSim({...sim,cycle_number:Number(e.target.value)})}/></Field></div><button className={styles.primary}>Run simulation</button>
  {quote&&<><Table columns={['Promotion','Eligible','Reason']} rows={quote.promotions_evaluated.map(p=>[p.code,p.eligible?'Yes':'No',p.reason||'Applied'])}/><div className={styles.grid}>{[['Subtotal',quote.subtotal_paise],['Discount',quote.discount_paise],['Shipping',quote.shipping_paise],['Total',quote.total_paise]].map(([label,amount])=><p key={label}>{label}: {amount} paise</p>)}</div><Table columns={['Adjustment / benefit','Type','Amount (paise)']} rows={[...quote.adjustments.map(a=>[a.label,a.type,a.amount_paise]),...quote.benefits.map(b=>[b.label,b.benefit_type,'—'])]}/></>}
  </form>
 </section>;
}

