"use client";
import { useState } from 'react';
import { resolvedVariableKeys } from '../../lib/communications/variables';
import type { Condition } from '../../lib/communications/dsl';
import { Field,styles,api } from './shared';
import ConditionEditor from './ConditionEditor';
export type RuleRow={id:string;name:string;description:string;version:number;status:string;trigger_type:string;trigger_event_type:string|null;cron_expression:string|null;timezone:string;condition_config:Condition;action_config:{templates:Record<string,string>;variables:Record<string,unknown>;abandoned_cart:boolean;offer_id?:string};frequency_cap:{weekly:number;cooldown_hours:number};quiet_hours:{start:number;end:number};priority:number;valid_from:string|null;valid_until:string|null;next_run_at:string|null;last_status:string|null;last_completed_at:string|null;};
export type VersionRow={id:string;template_id:string;version:number;status:string;channel:string;category:string;subject:string;html_content:string;text_content:string;parameter_schema:{required:string[];body_parameters:string[]};structured_content:Record<string,unknown>;};
export default function RuleEditor({initial,versions,onSave,onCancel}:{initial:RuleRow|null;versions:VersionRow[];onSave:()=>void;onCancel:()=>void}){
 const [v,set]=useState<Omit<RuleRow,'id'|'version'|'next_run_at'|'last_status'|'last_completed_at'>>(initial?{name:initial.name,description:initial.description||'',status:initial.status,trigger_type:initial.trigger_type,trigger_event_type:initial.trigger_event_type,cron_expression:initial.cron_expression,timezone:initial.timezone,condition_config:initial.condition_config,action_config:initial.action_config,frequency_cap:initial.frequency_cap,quiet_hours:initial.quiet_hours,priority:initial.priority,valid_from:initial.valid_from,valid_until:initial.valid_until}:{name:'',description:'',status:'DRAFT',trigger_type:'SCHEDULE',trigger_event_type:null,cron_expression:'0 10 * * 0',timezone:'Asia/Kolkata',condition_config:{all:[]},action_config:{templates:{},variables:{},abandoned_cart:false},frequency_cap:{weekly:3,cooldown_hours:24},quiet_hours:{start:21,end:9},priority:0,valid_from:null,valid_until:null});
 const [notice,message]=useState('');const [busy,working]=useState(false);
 const update=(key: keyof typeof v,value:unknown)=>set({...v,[key]:value});
 const parameters=[...new Set(versions.filter(t=>Object.values(v.action_config.templates).includes(t.id)).flatMap(t=>t.parameter_schema.required||[]))];
 async function action(operation:string,input:unknown){try{const r=await api('/api/admin/communications',{operation,input});message(typeof r.data==='object'?JSON.stringify(r.data):String(r.data));}catch(e){message((e as Error).message);}}
 return <form className={styles.panel} onSubmit={async e=>{e.preventDefault();working(true);try{await api('/api/admin/communications',{operation:'SAVE_RULE',input:{...(initial?.id?{id:initial.id,expected_version:initial.version}:{}),rule:v}});onSave();}catch(error){message((error as Error).message);}finally{working(false);}}}>
  <h2>{initial?.id?'Edit rule':'Create rule'}</h2><div className={styles.grid}>
   <Field label="Rule name"><input required value={v.name} onChange={e=>update('name',e.target.value)}/></Field>
   <Field label="Status"><select value={v.status} onChange={e=>update('status',e.target.value)}>{['DRAFT','ACTIVE','PAUSED','ARCHIVED'].map(s=><option key={s}>{s}</option>)}</select></Field>
   <Field label="Trigger"><select value={v.trigger_type} onChange={e=>update('trigger_type',e.target.value)}>{['EVENT','SCHEDULE','MANUAL'].map(s=><option key={s}>{s}</option>)}</select></Field>
   <Field label="Timezone"><input value={v.timezone} onChange={e=>update('timezone',e.target.value)} required/></Field>
  </div><Field label="Description"><input value={v.description} onChange={e=>update('description',e.target.value)}/></Field>
  {v.trigger_type==='EVENT'&&<Field label="Business event"><select required value={v.trigger_event_type||''} onChange={e=>update('trigger_event_type',e.target.value)}><option value="">Choose an event</option>{['customer.message.created','commerce.order.confirmed','commerce.payment.changed','commerce.subscription.changed','commerce.shipment.changed'].map(s=><option key={s}>{s}</option>)}</select></Field>}
  {v.trigger_type==='SCHEDULE'&&<div className={styles.panel}><h2>Schedule</h2><div className={styles.grid}>
   <Field label="Common schedule"><select value={['0 10 * * 0','0 10 * * *','0 10 1 * *'].includes(v.cron_expression||'')?v.cron_expression!:'advanced'} onChange={e=>{if(e.target.value!=='advanced')update('cron_expression',e.target.value);}}><option value="0 10 * * 0">Sunday at 10:00</option><option value="0 10 * * *">Daily at 10:00</option><option value="0 10 1 * *">First of month at 10:00</option><option value="advanced">Advanced</option></select></Field>
   <Field label="Advanced cron"><input value={v.cron_expression||''} onChange={e=>update('cron_expression',e.target.value)}/></Field></div>
   <button type="button" onClick={()=>action('NEXT_RUNS',{expression:v.cron_expression,timezone:v.timezone})}>Show next 5 runs</button><p className={styles.small}>Execution follows the configured dispatcher cadence. Configure the signed QStash schedule for minute-level scheduling.</p>
  </div>}
  <h2>Audience</h2><ConditionEditor value={v.condition_config} onChange={c=>update('condition_config',c)}/>
  <h2>Channels and templates</h2><div className={styles.grid}>{['EMAIL','WHATSAPP','SMS','LEMLIST'].map(channel=><Field key={channel} label={channel}><select value={v.action_config.templates[channel]||''} onChange={e=>{const templates={...v.action_config.templates};if(e.target.value)templates[channel]=e.target.value;else delete templates[channel];update('action_config',{...v.action_config,templates});}}><option value="">Do not send</option>{versions.filter(t=>t.channel===channel&&t.status==='ACTIVE').map(t=><option value={t.id} key={t.id}>{t.subject||t.template_id.slice(0,8)} · v{t.version} · {t.category}</option>)}</select></Field>)}</div>
  <label><input type="checkbox" checked={v.action_config.abandoned_cart} onChange={e=>update('action_config',{...v.action_config,abandoned_cart:e.target.checked})}/>Suppress if the cart converted</label>
  <h2>Content variables</h2><p className={styles.small}>Customer name, message text and declared order/payment/subscription fields are resolved from the server subject. Other values below are campaign constants; do not put private contact details in them.</p><div className={styles.grid}>{parameters.filter(key=>!resolvedVariableKeys.has(key)).map(key=><Field key={key} label={key}><input required value={String(v.action_config.variables[key]??'')} onChange={e=>update('action_config',{...v.action_config,variables:{...v.action_config.variables,[key]:e.target.value}})}/></Field>)}</div>
  <div className={styles.grid}><Field label="Priority"><input type="number" min={-100} max={100} value={v.priority} onChange={e=>update('priority',Number(e.target.value))}/></Field><Field label="Valid from (ISO timestamp, optional)"><input value={v.valid_from||''} placeholder="2026-12-01T00:00:00Z" onChange={e=>update('valid_from',e.target.value||null)}/></Field><Field label="Valid until (ISO timestamp, optional)"><input value={v.valid_until||''} placeholder="2026-12-31T23:59:59Z" onChange={e=>update('valid_until',e.target.value||null)}/></Field><Field label="Offer reference (optional)"><input value={v.action_config.offer_id||''} onChange={e=>{const action={...v.action_config};if(e.target.value)action.offer_id=e.target.value;else delete action.offer_id;update('action_config',action);}}/></Field></div>
  <div className={styles.grid}><Field label="Weekly marketing cap"><input type="number" min={1} max={10} value={v.frequency_cap.weekly} onChange={e=>update('frequency_cap',{...v.frequency_cap,weekly:Number(e.target.value)})}/></Field><Field label="Cooldown (hours)"><input type="number" min={1} value={v.frequency_cap.cooldown_hours} onChange={e=>update('frequency_cap',{...v.frequency_cap,cooldown_hours:Number(e.target.value)})}/></Field><Field label="Quiet hours start"><input type="number" min={0} max={23} value={v.quiet_hours.start} onChange={e=>update('quiet_hours',{...v.quiet_hours,start:Number(e.target.value)})}/></Field><Field label="Quiet hours end"><input type="number" min={0} max={23} value={v.quiet_hours.end} onChange={e=>update('quiet_hours',{...v.quiet_hours,end:Number(e.target.value)})}/></Field></div>
  <div className={styles.toolbar}><button type="button" onClick={()=>action('PREVIEW_AUDIENCE',{condition:v.condition_config})}>Preview audience (bounded)</button><button className={styles.primary} disabled={busy}>Save {v.status==='ACTIVE'?'and publish':'rule'}</button><button type="button" onClick={onCancel}>Cancel</button></div>
  {notice&&<p role="status" className={styles.notice}>{notice}</p>}
 </form>;
}

