"use client";
import { useState } from 'react';
import { Field,styles,api } from './shared';
import type { VersionRow } from './RuleEditor';
export default function TemplateEditor({initial,onSaved,onCancel}:{initial:(VersionRow&{logical_key?:string;name?:string})|null;onSaved:()=>void;onCancel:()=>void}){
 const body=(Array.isArray(initial?.structured_content.components)?initial.structured_content.components:[]).find((c:{type?:string;text?:string})=>c.type==='BODY');
 const [v,set]=useState({logical_key:initial?.logical_key||'',name:initial?.name||'',channel:initial?.channel||'EMAIL',category:initial?.category||'MARKETING',subject:initial?.subject||'',html_content:initial?.html_content||'',text_content:initial?.text_content||'',change_reason:'',required:(initial?.parameter_schema.required||[]).join(', '),body_parameters:(initial?.parameter_schema.body_parameters||[]).join(', '),whatsapp_body:body?.text||''});
 const [preview,showPreview]=useState<{html:string;text:string;assets:string[]}|null>(null);const [width,setWidth]=useState('100%');const [notice,message]=useState('');const [busy,working]=useState(false);
 const update=(key:keyof typeof v,value:string)=>set({...v,[key]:value});const keys=(s:string)=>s.split(',').map(k=>k.trim()).filter(Boolean);
 async function render(){try{const result=await api('/api/admin/communications',{operation:'PREVIEW_EMAIL',input:{html:v.html_content,variables:Object.fromEntries(keys(v.required).map(k=>[k,`[${k}]`]))}});showPreview(result.data);message('Variables and assets validated.');}catch(e){message((e as Error).message);}}
 return <form className={styles.panel} onSubmit={async e=>{e.preventDefault();working(true);try{await api('/api/admin/communications',{operation:'SAVE_TEMPLATE',input:{logical_key:v.logical_key,name:v.name,channel:v.channel,category:v.category,subject:v.subject,html_content:v.html_content,text_content:v.text_content,parameter_schema:{required:v.channel==='WHATSAPP'&&v.category==='AUTHENTICATION'?['otp']:keys(v.required),body_parameters:v.channel==='WHATSAPP'&&v.category==='AUTHENTICATION'?['otp']:keys(v.body_parameters)},structured_content:v.channel==='WHATSAPP'?{components:v.category==='AUTHENTICATION'?[{type:'BODY',add_security_recommendation:true},{type:'FOOTER',code_expiration_minutes:5},{type:'BUTTONS',buttons:[{type:'OTP',otp_type:'COPY_CODE',text:'Copy code'}]}]:[{type:'BODY',text:v.whatsapp_body}]}:{},change_reason:v.change_reason}});onSaved();}catch(e){message((e as Error).message);}finally{working(false);}}}>
  <h2>{initial?'Create next immutable version':'New template'}</h2><div className={styles.grid}>
   <Field label="Logical key"><input required value={v.logical_key} pattern="[A-Z0-9_]+" onChange={e=>update('logical_key',e.target.value)}/></Field><Field label="Name"><input required value={v.name} onChange={e=>update('name',e.target.value)}/></Field>
   <Field label="Channel"><select value={v.channel} onChange={e=>update('channel',e.target.value)}>{['EMAIL','WHATSAPP','SMS','LEMLIST'].map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Category"><select value={v.category} onChange={e=>update('category',e.target.value)}>{['MARKETING','TRANSACTIONAL','AUTHENTICATION'].map(c=><option key={c}>{c}</option>)}</select></Field>
   <Field label="Subject"><input value={v.subject} onChange={e=>update('subject',e.target.value)}/></Field><Field label="Required variables (comma separated)"><input value={v.required} onChange={e=>update('required',e.target.value)} placeholder="name, order_number"/></Field>
  </div>
  {(v.channel==='EMAIL'||v.channel==='LEMLIST')&&<><Field label="Paste HTML"><textarea spellCheck={false} value={v.html_content} onChange={e=>update('html_content',e.target.value)}/></Field><Field label="Upload .html"><input type="file" accept=".html,text/html" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>200000||!f.name.endsWith('.html')){message('Choose an HTML file smaller than 200 KB.');return;}update('html_content',await f.text());}}/></Field><div className={styles.toolbar}><button type="button" onClick={render}>Validate and preview</button><button type="button" onClick={()=>setWidth('100%')}>Desktop</button><button type="button" onClick={()=>setWidth('375px')}>Mobile</button></div>{preview&&<><iframe title="Sanitized email preview" sandbox="" className={styles.preview} style={{maxWidth:width}} srcDoc={preview.html}/><details><summary>Plain text and linked assets</summary><p>{preview.text}</p><ul>{preview.assets.map(url=><li key={url}>{url}</li>)}</ul></details></>}</>}
  {v.channel==='WHATSAPP'&&<>{v.category==='AUTHENTICATION'?<p>Uses Meta’s authentication format with one OTP, a copy-code button and five-minute expiry. Meta owns approval of the generated text.</p>:<><Field label="Meta body content (use numbered parameters)"><textarea required value={v.whatsapp_body} onChange={e=>update('whatsapp_body',e.target.value)} placeholder="Hello {{1}}, your order {{2}} is confirmed."/></Field><Field label="Body parameter order"><input value={v.body_parameters} onChange={e=>update('body_parameters',e.target.value)} placeholder="name, order_number"/></Field></>}<p>Production continues using the previous approved version until this version is approved and activated.</p></>}
  <Field label="Plain text"><textarea value={v.text_content} onChange={e=>update('text_content',e.target.value)}/></Field><Field label="Change reason"><input required value={v.change_reason} onChange={e=>update('change_reason',e.target.value)}/></Field>
  <div className={styles.toolbar}><button disabled={busy} className={styles.primary}>Save draft version</button><button type="button" onClick={onCancel}>Cancel</button></div>{notice&&<p role="status" className={styles.notice}>{notice}</p>}
 </form>;
}
