import { beforeEach,describe,expect,it,vi } from 'vitest';
const record=vi.hoisted(()=>vi.fn());vi.mock('@/lib/communications/webhooks',()=>({recordProviderEvent:record}));
beforeEach(()=>{record.mockReset();record.mockResolvedValue(undefined);process.env.MSG91_COMMUNICATION_WEBHOOK_TOKEN='sms-test';process.env.LEMLIST_COMMUNICATION_WEBHOOK_TOKEN='lemlist-test';});
const invoke=async(provider:string,payload:unknown,token?:string)=>{const {POST}=await import('../../app/api/communications/webhooks/[provider]/route');return POST(new Request(`https://dashboard.test/api/communications/webhooks/${provider}`,{method:'POST',headers:{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})},body:JSON.stringify(payload)}),{params:Promise.resolve({provider})});};
describe('native provider callbacks',()=>{
 it('accepts MSG91 request IDs and documented delivery codes with an authenticated header',async()=>{const response=await invoke('msg91',{requestId:'sms-request',status:'1',deliveryTime:'2026-10-07T10:00:00+05:30'},'sms-test');expect(response.status).toBe(200);expect(record).toHaveBeenCalledWith('MSG91','sms-request','DELIVERED','2026-10-07T04:30:00.000Z',undefined,undefined);});
 it('authenticates Lemlist by its documented body secret and correlates campaign/step to lead ID',async()=>{const response=await invoke('lemlist',{secret:'lemlist-test',_id:'activity',type:'emailsOpened',leadId:'lead',campaignId:'campaign',stepId:'step',createdAt:'2026-10-07T00:00:00Z',leadEmail:'controlled@example.test'});expect(response.status).toBe(200);expect(record).toHaveBeenCalledWith('LEMLIST','lead','OPENED','2026-10-07T00:00:00.000Z','controlled@example.test',{eventId:'activity',campaignId:'campaign',stepId:'step'});});
 it('rejects spoofed callbacks and ignores unrelated authenticated Lemlist activity',async()=>{expect((await invoke('lemlist',{secret:'wrong',type:'emailsSent'})).status).toBe(401);expect(record).not.toHaveBeenCalled();expect((await invoke('lemlist',{secret:'lemlist-test',type:'linkedinSent'})).status).toBe(200);expect(record).not.toHaveBeenCalled();});
 it('requires unambiguous SMS timestamps and returns retryable status when persistence fails',async()=>{expect((await invoke('msg91',{requestId:'sms-request',status:'1',deliveryTime:'2026-10-07 10:00:00'},'sms-test')).status).toBe(400);record.mockRejectedValueOnce(new Error('database down'));expect((await invoke('msg91',{message_id:'sms-request',status:'DELIVERED',timestamp:'2026-10-07T00:00:00Z'},'sms-test')).status).toBe(503);});
});
